### ISSUE TITLE
Does this support unpublishing?

### ISSUE THREAD

**Issue by stephenhuh** [ModiiMedia/contentful-hugo#17]
Hey there,

We're currently using this library to support a hugo website, but it seems that while writes (edits and new content) on Contentful seem to work well. 'Unpublishing' content doesnt delete entries written to the repository, therefore leaving unpublished content in source. 

Is there a recommended way to go about resolving this?

**Comment by joshmossas** [comment]
Hey @stephenhuh this library works by pulling all the currently published entries in Contentful and overriding existing files. As a result it doesn't keep track of entries that have been unpublished. 

The way I've usually accounted for unpublished entries is to keep the files generated by contentful-hugo in the .gitignore file. Here's simple example I had used on a previous project.

```gitignore
# ignore all .md files in /content except list pages in subdirectories (_index.md)
content/*/[!_]*.md
content/*/*/*
content/*.md
```

This works really well when you use a CI pipeline or something like Netlify since it'll just pull from your git repo then generate all the markdown files at build time.

However it won't work if your workflow involves building the site locally and then deploying it somewhere.

**Comment by stephenhuh** [comment]
@joshmossas this is good enough for us as well! -- thank you for the response
